#include <stdio.h>
int main(){
    int a,b[100][100],c,d,y,z;
    scanf("%d",&a);
    getchar();
    for(z=0;z<a;z=z+1){
        for(y=0;y<a;y=y+1){
            b[z][y]=getchar();
        }
        getchar();
    }
    d=0;
    for(z=0;z<a;z=z+1){
        c=0;
        y=0;
        while(y<a){
            if(b[z][y]=='.'){
                c=c+1;
            }
            else{
                if(c>=2){
                    d=d+1;
                }
                c=0;
            }
            y=y+1;
        }
        if(y==a){
            if(c>=2){
                d=d+1;
            }
        }
    }
    printf("%d ",d);
    d=0;
    for(z=0;z<a;z=z+1){
        c=0;
        y=0;
        while(y<a){
            if(b[y][z]=='.'){
                c=c+1;
            }
            else{
                if(c>=2){
                    d=d+1;
                }
                c=0;
            }
            y=y+1;
        }
        if(y==a){
            if(c>=2){
                d=d+1;
            }
        }
    }
    printf("%d",d);
}