#include <stdio.h>
int main(){
    int a,b,c[6],d=0,e,f,x,y,z;
    scanf("%d",&a);
    for(z=0;z<a;z=z+1){
        for(y=0;y<6;y=y+1){
            c[y]=0;
        }
        for(y=0;y<4;y=y+1){
            scanf("%d",&b);
            c[b-1]=c[b-1]+1;
        }
        f=0;
        for(y=5;y>=0;y=y-1){
            if(c[y]==4){
                e=55000+y*5000;
                if(e>d){
                    d=e;
                }
                f=1;
                break;
            }
        }
        if(f==0){
            for(y=5;y>=0;y=y-1){
                if(c[y]==3){
                    e=11000+y*1000;
                    if(e>d){
                        d=e;
                    }
                    f=1;
                    break;
                }
            }
        }
        if(f==0){
            for(y=5;y>=0;y=y-1){
                if(f==1){
                    break;
                }
                if(c[y]==2){
                    for(x=5;x>=0;x=x-1){
                        if(x==y){
                            continue;
                        }
                        if(c[x]==2){
                            e=3000+500*x+500*y;
                            if(e>d){
                                d=e;
                            }
                            f=1;
                            break;
                        }
                    }
                    if(f==0){
                        e=1100+100*y;
                        if(e>d){
                            d=e;
                        }
                        f=1;
                        break;
                    }
                }
            }
        }
        if(f==0){
            for(y=5;y>=0;y=y-1){
                if(c[y]==1){
                    e=100+y*100;
                    if(e>d){
                        d=e;
                    }
                    break;
                }
            }
        }
    }
    printf("%d",d);
}