#include <stdio.h>
#include <stdlib.h>
int a,b,**c,**d,e[2],f[2],h[225001][2],k[225001][2];
int m(int g,int i,int j){
    int n,l=3001;
    if(j<d[g][i]){
        j=d[g][i];
    }
    if(j<c[g][i]){
        if((g==f[0])&&(i==f[1])){
            return j;
        }
        c[g][i]=j;
        if(g!=0){
            n=m(g-1,i,j);
            if(n<l){
                l=n;
            }
        }
        if(i!=0){
            n=m(g,i-1,j);
            if(n<l){
                l=n;
            }
        }
        if(g!=a-1){
            n=m(g+1,i,j);
            if(n<l){
                l=n;
            }
        }
        if(i!=b-1){
            n=m(g,i+1,j);
            if(n<l){
                l=n;
            }
        }
    }
    return l;
}
int main(){
    int g=0,i=0,j=1,l=0,y,z;
    scanf("%d %d",&a,&b);
    c=(int**)malloc(sizeof(int*)*a);
    c[0]=(int*)malloc(sizeof(int)*a*b);
    d=(int**)malloc(sizeof(int*)*a);
    d[0]=(int*)malloc(sizeof(int)*a*b);
    for(z=1;z<a;z=z+1){
        c[z]=c[z-1]+b;
    }
    for(z=1;z<a;z=z+1){
        d[z]=d[z-1]+b;
    }
    for(z=0;z<a;z=z+1){
        for(y=0;y<b;y=y+1){
            c[z][y]=3001;
        }
    }
    getchar();
    for(z=0;z<a;z=z+1){
        for(y=0;y<b;y=y+1){
            d[z][y]=getchar();
            if(d[z][y]=='.'){
                d[z][y]=0;
                h[i][0]=z;
                h[i][1]=y;
                i=i+1;
            }
            else if(d[z][y]=='L'){
                if(g==0){
                    e[0]=z;
                    e[1]=y;
                    g=1;
                }
                else{
                    f[0]=z;
                    f[1]=y;
                }
                d[z][y]=0;
                h[i][0]=z;
                h[i][1]=y;
                i=i+1;
            }
            else{
                d[z][y]=3001;
            }
        }
        getchar();
    }
    while(1){
        for(i=i-1;i>=0;i=i-1){
            if(h[i][0]!=0){
                if(d[h[i][0]-1][h[i][1]]>j){
                    d[h[i][0]-1][h[i][1]]=j;
                    k[l][0]=h[i][0]-1;
                    k[l][1]=h[i][1];
                    l=l+1;
                }
            }
            if(h[i][1]!=0){
                if(d[h[i][0]][h[i][1]-1]>j){
                    d[h[i][0]][h[i][1]-1]=j;
                    k[l][0]=h[i][0];
                    k[l][1]=h[i][1]-1;
                    l=l+1;
                }
            }
            if(h[i][0]!=a-1){
                if(d[h[i][0]+1][h[i][1]]>j){
                    d[h[i][0]+1][h[i][1]]=j;
                    k[l][0]=h[i][0]+1;
                    k[l][1]=h[i][1];
                    l=l+1;
                }
            }
            if(h[i][1]!=b-1){
                if(d[h[i][0]][h[i][1]+1]>j){
                    d[h[i][0]][h[i][1]+1]=j;
                    k[l][0]=h[i][0];
                    k[l][1]=h[i][1]+1;
                    l=l+1;
                }
            }
        }
        i=i+1;
        for(l=l-1;l>=0;l=l-1){
            h[i][0]=k[l][0];
            h[i][1]=k[l][1];
            i=i+1;
        }
        l=0;
        if(i==0){
            break;
        }
        j=j+1;
    }
    printf("%d",m(e[0],e[1],0));
}